apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-credentials
  namespace: tlmc-player
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: aab++112
  POSTGRES_DB: keycloak
  POSTGRES_HOST: keycloak-pgsql-clusterip.tlmc-player.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: tlmc-player
type: Opaque
stringData:
  # CHANGE ME
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
