apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pgsql-pv
  namespace: tlmc-player
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/k8s_data/pgsql-backend-pv1"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pgsql-pv-claim
  namespace: tlmc-player
spec:
  resources:
    requests:
      storage: 5Gi
  # storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
