apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-pgsql-depl
  namespace: tlmc-player
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pgsql-depl

  template:
    metadata:
      labels:
        app: backend-pgsql-depl

    spec:
      containers:
        - name: backend-pgsql-depl
          image: postgres:15.4-bullseye
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgrespw

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb

      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: backend-pgsql-pv-claim
