apiVersion: v1
kind: Service
metadata:
  name: backend-api-clusterip
  namespace: tlmc-player
spec:
  type: ClusterIP
  selector:
    app: backend-api
  ports:
    - name: http-backend-api
      port: 80
      protocol: TCP
      targetPort: 80
      appProtocol: HTTP
