apiVersion: v1
kind: Service
metadata:
  name: backend-pgsql-clusterip
  namespace: tlmc-player
spec:
  type: ClusterIP
  selector:
    app: backend-pgsql-depl
  ports:
    - name: tcp-backend-pgsql-db-port
      protocol: TCP
      port: 5432
      targetPort: 5432
      appProtocol: TCP
