version: '3.4'

services:
  musicdataservice:
    image: ${DOCKER_REGISTRY-}musicdataservice
    build:
      context: .
      dockerfile: MusicDataService/Dockerfile

  playlistservice:
    image: ${DOCKER_REGISTRY-}playlistservice
    build:
      context: .
      dockerfile: PlaylistService/Dockerfile


  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 25432:5432
    volumes:
      - data:/var/lib/postgresql

volumes:
  data:
