apiVersion: v1
kind: PersistentVolume
metadata:
  name: musicdata-pgsql-pv
  namespace: tlmc-player
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/k8s_data/pgsql-musicdata-pv1"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musicdata-pgsql-pv-claim
spec:
  resources:
    requests:
      storage: 5Gi
  # storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
