apiVersion: v1
kind: Service
metadata:
  name: musicdata-api-clusterip
  namespace: tlmc-player
spec:
  type: ClusterIP
  selector:
    app: musicdata-api
  ports:
    - name: http-musicdata-api
      port: 80
      protocol: TCP
      targetPort: 80
      appProtocol: HTTP
