apiVersion: v1
kind: Service
metadata:
  name: musicdata-pgsql-clusterip
  namespace: tlmc-player
spec:
  type: ClusterIP
  selector:
    app: musicdata-pgsql-depl
  ports:
  - name: tcp-musicdata-pgsql-db-port
    protocol: TCP
    port: 5432
    targetPort: 5432
    appProtocol: TCP

# apiVersion: v1
# kind: Service
# metadata:
#   name: pgsql-musicdata-loadbalancer
# spec:
#   type: LoadBalancer
#   selector:
#     app: musicdata-pgsql-depl
#   ports:
#     - name: musicdata-pgsql-db-port
#       protocol: TCP
#       port: 15432
#       targetPort: 5432
