---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pgsql-data
  namespace: tlmc-player
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-pgsql
  namespace: tlmc-player
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak-pgsql
  template:
    metadata:
      labels:
        app: keycloak-pgsql
    spec:
      containers:
        - name: postgres
          image: postgres:15.4-bullseye
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-pgsql-credentials
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "keycloak", "-d", "keycloak"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: keycloak-pgsql-data
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-pgsql-clusterip
  namespace: tlmc-player
spec:
  type: ClusterIP
  selector:
    app: keycloak-pgsql
  ports:
    - name: tcp-postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
