apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
  labels:
    name: ingress-srv

spec:
  rules:
  - host: nms.testing.internal.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: musicdata-api-clusterip
            port: 
              number: 80
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: auth-api-clusterip
            port: 
              number: 80