apiVersion: v1
kind: PersistentVolume
metadata:
  name: musicsearch-es-pv
  namespace: tlmc-player
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/k8s_data/es-musicsearch-pv1"

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musicsearch-es-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
