apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicsearch-redis
  namespace: tlmc-player
spec:
  selector:
    matchLabels:
      app: musicsearch-redis
  template:
    metadata:
      labels:
        app: musicsearch-redis
    spec:
      containers:
      - name: musicsearch-redis
        image: redis:latest
        command: ["redis-server"]
        args: ["--requirepass", "EwJRwkLvJQ76eow5N4kofRj61vziS9j5kQzytxg9PAIWEVG3JWM8zAD3CqPV9eQ"]
        ports:
        - containerPort: 6379
