apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api
  namespace: tlmc-player
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-api
  template:
    metadata:
      labels:
        app: search-api
    spec:
      containers:
      - name: search-api
        image: sqzd269/search-api:latest
        env:
          - name: ElasticSearch__ClusterNodes__0
            value: "http://musicsearch-es-clusterip.tlmc-player.svc.cluster.local:9200"
          - name: ElasticSearch__Username
            value: "elastic"
          - name: ElasticSearch__Password
            value: "changeme"