apiVersion: v1
kind: Service
metadata:
  name: search-api-clusterip
  namespace: tlmc-player
spec:
  type: ClusterIP
  selector:
    app: search-api
  ports:
    - name: http-search-api
      port: 80
      protocol: TCP
      targetPort: 80
      appProtocol: HTTP
