apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicsearch-pgsync
  namespace: tlmc-player
spec:
  selector:
    matchLabels:
      app: musicsearch-pgsync
  template:
    metadata:
      labels:
        app: musicsearch-pgsync
    spec:
      containers:
      - name: musicsearch-pgsync
        image: sqzd269/search-pgsync:latest
        command: ["./runserver.sh"]
        env:
          - name: PG_USER
            value: postgres
          - name: PG_HOST
            value: musicdata-pgsql-clusterip.tlmc-player.svc.cluster.local
          - name: PG_PORT
            value: "5432"
          - name: PG_PASSWORD
            value: postgrespw
          - name: LOG_LEVEL
            value: INFO
          - name: ELASTICSEARCH_PORT
            value: "9200"
          - name: ELASTICSEARCH_SCHEME
            value: http
          - name: ELASTICSEARCH_HOST
            value: musicsearch-es-clusterip.tlmc-player.svc.cluster.local
          - name: REDIS_HOST
            value: musicsearch-redis-clusterip.tlmc-player.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_AUTH
            value: EwJRwkLvJQ76eow5N4kofRj61vziS9j5kQzytxg9PAIWEVG3JWM8zAD3CqPV9eQ
          - name: ELASTICSEARCH
            value: "true"
          - name: OPENSEARCH
            value: "false"