apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicsearch-redis
  namespace: tlmc-player
spec:
  selector:
    matchLabels:
      app: musicsearch-redis
  template:
    metadata:
      labels:
        app: musicsearch-redis
    spec:
      containers:
      - name: musicsearch-redis
        image: redis:lastest
        ports:
        - containerPort: 6379
