// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataService/SyncDataService/Grpc/Proto/auth.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace AuthenticationService.SyncDataService.Grpc.Proto {
  public static partial class GrpcAuthenticationService
  {
    static readonly string __ServiceName = "GrpcAuthenticationService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::AuthenticationService.SyncDataService.Grpc.Proto.GetJwtPublicKeyRequest> __Marshaller_GetJwtPublicKeyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AuthenticationService.SyncDataService.Grpc.Proto.GetJwtPublicKeyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::AuthenticationService.SyncDataService.Grpc.Proto.JwtPublicKeyResponse> __Marshaller_JwtPublicKeyResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AuthenticationService.SyncDataService.Grpc.Proto.JwtPublicKeyResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::AuthenticationService.SyncDataService.Grpc.Proto.GetJwtPublicKeyRequest, global::AuthenticationService.SyncDataService.Grpc.Proto.JwtPublicKeyResponse> __Method_GetJwtPublicKey = new grpc::Method<global::AuthenticationService.SyncDataService.Grpc.Proto.GetJwtPublicKeyRequest, global::AuthenticationService.SyncDataService.Grpc.Proto.JwtPublicKeyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetJwtPublicKey",
        __Marshaller_GetJwtPublicKeyRequest,
        __Marshaller_JwtPublicKeyResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AuthenticationService.SyncDataService.Grpc.Proto.AuthReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for GrpcAuthenticationService</summary>
    public partial class GrpcAuthenticationServiceClient : grpc::ClientBase<GrpcAuthenticationServiceClient>
    {
      /// <summary>Creates a new client for GrpcAuthenticationService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public GrpcAuthenticationServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GrpcAuthenticationService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public GrpcAuthenticationServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected GrpcAuthenticationServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected GrpcAuthenticationServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::AuthenticationService.SyncDataService.Grpc.Proto.JwtPublicKeyResponse GetJwtPublicKey(global::AuthenticationService.SyncDataService.Grpc.Proto.GetJwtPublicKeyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetJwtPublicKey(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::AuthenticationService.SyncDataService.Grpc.Proto.JwtPublicKeyResponse GetJwtPublicKey(global::AuthenticationService.SyncDataService.Grpc.Proto.GetJwtPublicKeyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetJwtPublicKey, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::AuthenticationService.SyncDataService.Grpc.Proto.JwtPublicKeyResponse> GetJwtPublicKeyAsync(global::AuthenticationService.SyncDataService.Grpc.Proto.GetJwtPublicKeyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetJwtPublicKeyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::AuthenticationService.SyncDataService.Grpc.Proto.JwtPublicKeyResponse> GetJwtPublicKeyAsync(global::AuthenticationService.SyncDataService.Grpc.Proto.GetJwtPublicKeyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetJwtPublicKey, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override GrpcAuthenticationServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GrpcAuthenticationServiceClient(configuration);
      }
    }

  }
}
#endregion
