// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using TlmcPlayerBackend.Data;
using TlmcPlayerBackend.Models.MusicData;
using TlmcPlayerBackend.Models.Playlist;

#nullable disable

namespace TlmcPlayerBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731222522_Phase0RecSignals")]
    partial class Phase0RecSignals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "credit_role", new[] { "arranger", "composer", "lyricist", "performer", "staff", "vocalist" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "play_source", new[] { "album", "map", "playlist", "queue", "radio", "recommended", "search", "shuffle", "similar", "unknown" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "playlist_kind", new[] { "favorite", "normal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "playlist_visibility", new[] { "private", "public", "unlisted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage_root", new[] { "generated", "library", "thumbnail" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Artwork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Colors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("colors");

                    b.Property<Guid>("SourceAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_asset_id");

                    b.HasKey("Id")
                        .HasName("pk_artwork");

                    b.HasIndex("SourceAssetId")
                        .HasDatabaseName("ix_artwork_source_asset_id");

                    b.ToTable("artwork", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.ArtworkVariant", b =>
                {
                    b.Property<Guid>("ArtworkId")
                        .HasColumnType("uuid")
                        .HasColumnName("artwork_id");

                    b.Property<short>("SizePx")
                        .HasColumnType("smallint")
                        .HasColumnName("size_px");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.HasKey("ArtworkId", "SizePx")
                        .HasName("pk_artwork_variant");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_artwork_variant_asset_id");

                    b.ToTable("artwork_variant", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Mime")
                        .HasColumnType("text")
                        .HasColumnName("mime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<StorageRoot>("Root")
                        .HasColumnType("storage_root")
                        .HasColumnName("root");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("pk_asset");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_asset_content_hash")
                        .HasFilter("content_hash IS NOT NULL");

                    b.HasIndex("Root", "StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_root_storage_key");

                    b.ToTable("asset", null, t =>
                        {
                            t.HasCheckConstraint("asset_storage_key_shape", "storage_key <> '' AND storage_key NOT LIKE '/%' AND storage_key !~ '(^|/)\\.\\.(/|$)'");
                        });
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Circle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Alias")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("alias");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.PrimitiveCollection<List<string>>("DataSource")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("data_source");

                    b.Property<DateOnly?>("Established")
                        .HasColumnType("date")
                        .HasColumnName("established");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TlmcReference")
                        .HasColumnType("text")
                        .HasColumnName("tlmc_reference");

                    b.HasKey("Id")
                        .HasName("pk_circle");

                    b.ToTable("circle", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.CircleWebsite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid")
                        .HasColumnName("circle_id");

                    b.Property<bool>("Invalid")
                        .HasColumnType("boolean")
                        .HasColumnName("invalid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_circle_website");

                    b.HasIndex("CircleId")
                        .HasDatabaseName("ix_circle_website_circle_id");

                    b.ToTable("circle_website", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Disc", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("DiscNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("disc_number");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.HasKey("Id")
                        .HasName("pk_disc");

                    b.HasIndex("ReleaseId", "DiscNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_disc_release_id_disc_number");

                    b.ToTable("disc", null, t =>
                        {
                            t.HasCheckConstraint("disc_number_positive", "disc_number >= 1");
                        });
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.EmbeddingConfig", b =>
                {
                    b.Property<bool>("Id")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("id");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int>("TrackCount")
                        .HasColumnType("integer")
                        .HasColumnName("track_count");

                    b.HasKey("Id")
                        .HasName("pk_embedding_config");

                    b.ToTable("embedding_config", null, t =>
                        {
                            t.HasCheckConstraint("embedding_config_single_row", "id");
                        });
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Lyrics", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ReferenceUrl")
                        .HasColumnType("text")
                        .HasColumnName("reference_url");

                    b.Property<List<LyricsVariant>>("Variants")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variants");

                    b.HasKey("Id")
                        .HasName("pk_lyrics");

                    b.ToTable("lyrics", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.OriginalSong", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_key");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("text")
                        .HasColumnName("external_ref");

                    b.Property<Guid>("OriginalWorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_work_id");

                    b.Property<LocalizedField>("Title")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.Property<short?>("TrackIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("track_index");

                    b.HasKey("Id")
                        .HasName("pk_original_song");

                    b.HasIndex("ExternalKey")
                        .IsUnique()
                        .HasDatabaseName("ix_original_song_external_key");

                    b.HasIndex("OriginalWorkId")
                        .HasDatabaseName("ix_original_song_original_work_id");

                    b.ToTable("original_song", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.OriginalWork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_key");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("text")
                        .HasColumnName("external_ref");

                    b.Property<LocalizedField>("FullName")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("full_name");

                    b.Property<LocalizedField>("ShortName")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("short_name");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_type");

                    b.HasKey("Id")
                        .HasName("pk_original_work");

                    b.HasIndex("ExternalKey")
                        .IsUnique()
                        .HasDatabaseName("ix_original_work_external_key");

                    b.ToTable("original_work", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArtworkId")
                        .HasColumnType("uuid")
                        .HasColumnName("artwork_id");

                    b.Property<string>("CatalogNumber")
                        .HasColumnType("text")
                        .HasColumnName("catalog_number");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<List<string>>("DataSources")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("data_sources");

                    b.Property<LocalizedField>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("NameSort")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("name_sort")
                        .HasComputedColumnSql("lower(name->>'default')", true);

                    b.Property<string>("ReleaseConvention")
                        .HasColumnType("text")
                        .HasColumnName("release_convention");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.PrimitiveCollection<List<string>>("TlmcRootReference")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tlmc_root_reference");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<List<string>>("Websites")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("websites");

                    b.HasKey("Id")
                        .HasName("pk_release");

                    b.HasIndex("ArtworkId")
                        .HasDatabaseName("ix_release_artwork_id");

                    b.HasIndex("CatalogNumber")
                        .HasDatabaseName("ix_release_catalog_number")
                        .HasFilter("catalog_number IS NOT NULL");

                    b.HasIndex("NameSort")
                        .HasDatabaseName("ix_release_name_sort");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("ix_release_release_date");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_release_updated_at");

                    b.ToTable("release", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.ReleaseCircle", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid")
                        .HasColumnName("circle_id");

                    b.Property<short>("Ordinal")
                        .HasColumnType("smallint")
                        .HasColumnName("ordinal");

                    b.HasKey("ReleaseId", "CircleId")
                        .HasName("pk_release_circle");

                    b.HasIndex("CircleId")
                        .HasDatabaseName("ix_release_circle_circle_id");

                    b.ToTable("release_circle", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.SimilarCircle", b =>
                {
                    b.Property<Guid>("AnchorCircleId")
                        .HasColumnType("uuid")
                        .HasColumnName("anchor_circle_id");

                    b.Property<Guid>("NeighborCircleId")
                        .HasColumnType("uuid")
                        .HasColumnName("neighbor_circle_id");

                    b.Property<short?>("RankKde")
                        .HasColumnType("smallint")
                        .HasColumnName("rank_kde");

                    b.Property<short?>("RankRaw")
                        .HasColumnType("smallint")
                        .HasColumnName("rank_raw");

                    b.Property<short?>("RankStyle")
                        .HasColumnType("smallint")
                        .HasColumnName("rank_style");

                    b.Property<float>("ScoreKde")
                        .HasColumnType("real")
                        .HasColumnName("score_kde");

                    b.Property<float>("ScoreRaw")
                        .HasColumnType("real")
                        .HasColumnName("score_raw");

                    b.Property<float>("ScoreStyle")
                        .HasColumnType("real")
                        .HasColumnName("score_style");

                    b.HasKey("AnchorCircleId", "NeighborCircleId")
                        .HasName("pk_similar_circle");

                    b.HasIndex("NeighborCircleId")
                        .HasDatabaseName("ix_similar_circle_neighbor_circle_id");

                    b.HasIndex("AnchorCircleId", "RankKde")
                        .IsUnique()
                        .HasDatabaseName("ix_similar_circle_anchor_circle_id_rank_kde")
                        .HasFilter("rank_kde IS NOT NULL");

                    b.HasIndex("AnchorCircleId", "RankRaw")
                        .IsUnique()
                        .HasDatabaseName("ix_similar_circle_anchor_circle_id_rank_raw")
                        .HasFilter("rank_raw IS NOT NULL");

                    b.HasIndex("AnchorCircleId", "RankStyle")
                        .IsUnique()
                        .HasDatabaseName("ix_similar_circle_anchor_circle_id_rank_style")
                        .HasFilter("rank_style IS NOT NULL");

                    b.ToTable("similar_circle", null, t =>
                        {
                            t.HasCheckConstraint("similar_circle_no_self", "anchor_circle_id <> neighbor_circle_id");

                            t.HasCheckConstraint("similar_circle_some_rank", "rank_style IS NOT NULL OR rank_raw IS NOT NULL OR rank_kde IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.SimilarRelease", b =>
                {
                    b.Property<Guid>("AnchorReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("anchor_release_id");

                    b.Property<Guid>("NeighborReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("neighbor_release_id");

                    b.Property<short?>("RankKde")
                        .HasColumnType("smallint")
                        .HasColumnName("rank_kde");

                    b.Property<short?>("RankRaw")
                        .HasColumnType("smallint")
                        .HasColumnName("rank_raw");

                    b.Property<short?>("RankStyle")
                        .HasColumnType("smallint")
                        .HasColumnName("rank_style");

                    b.Property<float>("ScoreKde")
                        .HasColumnType("real")
                        .HasColumnName("score_kde");

                    b.Property<float>("ScoreRaw")
                        .HasColumnType("real")
                        .HasColumnName("score_raw");

                    b.Property<float>("ScoreStyle")
                        .HasColumnType("real")
                        .HasColumnName("score_style");

                    b.HasKey("AnchorReleaseId", "NeighborReleaseId")
                        .HasName("pk_similar_release");

                    b.HasIndex("NeighborReleaseId")
                        .HasDatabaseName("ix_similar_release_neighbor_release_id");

                    b.HasIndex("AnchorReleaseId", "RankKde")
                        .IsUnique()
                        .HasDatabaseName("ix_similar_release_anchor_release_id_rank_kde")
                        .HasFilter("rank_kde IS NOT NULL");

                    b.HasIndex("AnchorReleaseId", "RankRaw")
                        .IsUnique()
                        .HasDatabaseName("ix_similar_release_anchor_release_id_rank_raw")
                        .HasFilter("rank_raw IS NOT NULL");

                    b.HasIndex("AnchorReleaseId", "RankStyle")
                        .IsUnique()
                        .HasDatabaseName("ix_similar_release_anchor_release_id_rank_style")
                        .HasFilter("rank_style IS NOT NULL");

                    b.ToTable("similar_release", null, t =>
                        {
                            t.HasCheckConstraint("similar_release_no_self", "anchor_release_id <> neighbor_release_id");

                            t.HasCheckConstraint("similar_release_some_rank", "rank_style IS NOT NULL OR rank_raw IS NOT NULL OR rank_kde IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.SimilarTrack", b =>
                {
                    b.Property<Guid>("AnchorTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("anchor_track_id");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint")
                        .HasColumnName("rank");

                    b.Property<Guid>("NeighborTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("neighbor_track_id");

                    b.Property<float>("Score")
                        .HasColumnType("real")
                        .HasColumnName("score");

                    b.HasKey("AnchorTrackId", "Rank")
                        .HasName("pk_similar_track");

                    b.HasIndex("NeighborTrackId")
                        .HasDatabaseName("ix_similar_track_neighbor_track_id");

                    b.ToTable("similar_track", null, t =>
                        {
                            t.HasCheckConstraint("similar_track_no_self", "anchor_track_id <> neighbor_track_id");

                            t.HasCheckConstraint("similar_track_rank_positive", "rank >= 1");
                        });
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameSort")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("name_sort")
                        .HasComputedColumnSql("lower(name)", true);

                    b.HasKey("Id")
                        .HasName("pk_tag");

                    b.HasIndex("NameSort")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_name_sort");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DiscId")
                        .HasColumnType("uuid")
                        .HasColumnName("disc_id");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<bool>("HasDash")
                        .HasColumnType("boolean")
                        .HasColumnName("has_dash");

                    b.PrimitiveCollection<List<short>>("HlsBitrates")
                        .IsRequired()
                        .HasColumnType("smallint[]")
                        .HasColumnName("hls_bitrates");

                    b.Property<Guid?>("LyricsId")
                        .HasColumnType("uuid")
                        .HasColumnName("lyrics_id");

                    b.Property<string>("MediaKey")
                        .HasColumnType("text")
                        .HasColumnName("media_key");

                    b.Property<LocalizedField>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("NameSort")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("name_sort")
                        .HasComputedColumnSql("lower(name->>'default')", true);

                    b.Property<bool?>("OriginalNonTouhou")
                        .HasColumnType("boolean")
                        .HasColumnName("original_non_touhou");

                    b.Property<Guid?>("SourceAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_asset_id");

                    b.Property<short>("TrackNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("track_number");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_track");

                    b.HasIndex("LyricsId")
                        .HasDatabaseName("ix_track_lyrics_id");

                    b.HasIndex("NameSort")
                        .HasDatabaseName("ix_track_name_sort");

                    b.HasIndex("SourceAssetId")
                        .HasDatabaseName("ix_track_source_asset_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_track_updated_at");

                    b.HasIndex("DiscId", "TrackNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_track_disc_id_track_number");

                    b.ToTable("track", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.TrackCredit", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<CreditRole>("Role")
                        .HasColumnType("credit_role")
                        .HasColumnName("role");

                    b.Property<short>("Ordinal")
                        .HasColumnType("smallint")
                        .HasColumnName("ordinal");

                    b.Property<string>("CreditName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("credit_name");

                    b.Property<string>("CreditNameSort")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("credit_name_sort")
                        .HasComputedColumnSql("lower(credit_name)", true);

                    b.HasKey("TrackId", "Role", "Ordinal")
                        .HasName("pk_track_credit");

                    b.HasIndex("CreditNameSort")
                        .HasDatabaseName("ix_track_credit_credit_name_sort");

                    b.ToTable("track_credit", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.TrackEmbedding", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Vector>("EmbeddingMean")
                        .IsRequired()
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding_mean");

                    b.Property<HalfVector>("EmbeddingMeanMax")
                        .IsRequired()
                        .HasColumnType("halfvec(2048)")
                        .HasColumnName("embedding_mean_max");

                    b.HasKey("TrackId")
                        .HasName("pk_track_embedding");

                    b.HasIndex("EmbeddingMean")
                        .HasDatabaseName("ix_track_embedding_embedding_mean");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EmbeddingMean"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("EmbeddingMean"), new[] { "vector_cosine_ops" });

                    b.HasIndex("EmbeddingMeanMax")
                        .HasDatabaseName("ix_track_embedding_embedding_mean_max");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EmbeddingMeanMax"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("EmbeddingMeanMax"), new[] { "halfvec_cosine_ops" });

                    b.ToTable("track_embedding", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.TrackMapCluster", b =>
                {
                    b.Property<short>("Cluster")
                        .HasColumnType("smallint")
                        .HasColumnName("cluster");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Cluster")
                        .HasName("pk_track_map_cluster");

                    b.ToTable("track_map_cluster", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.TrackMapPoint", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid?>("CircleId")
                        .HasColumnType("uuid")
                        .HasColumnName("circle_id");

                    b.Property<short>("Cluster")
                        .HasColumnType("smallint")
                        .HasColumnName("cluster");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.Property<float>("X")
                        .HasColumnType("real")
                        .HasColumnName("x");

                    b.Property<float>("Y")
                        .HasColumnType("real")
                        .HasColumnName("y");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("TrackId")
                        .HasName("pk_track_map");

                    b.HasIndex("CircleId")
                        .HasDatabaseName("ix_track_map_circle_id");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_track_map_work_id");

                    b.ToTable("track_map", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.TrackOriginalSong", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("OriginalSongId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_song_id");

                    b.HasKey("TrackId", "OriginalSongId")
                        .HasName("pk_track_original_song");

                    b.HasIndex("OriginalSongId", "TrackId")
                        .HasDatabaseName("ix_track_original_song_original_song_id_track_id");

                    b.ToTable("track_original_song", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.TrackTag", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("TrackId", "TagId")
                        .HasName("pk_track_tag");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_track_tag_tag_id");

                    b.ToTable("track_tag", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.Playlist.PlayEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int?>("MsPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("ms_played");

                    b.Property<DateTime>("PlayedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at")
                        .HasDefaultValueSql("now()");

                    b.Property<PlaySource>("Source")
                        .HasColumnType("play_source")
                        .HasColumnName("source");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_play_event");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_play_event_track_id");

                    b.HasIndex("UserId", "PlayedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_play_event_user_id_played_at");

                    b.HasIndex("UserId", "TrackId")
                        .HasDatabaseName("ix_play_event_user_id_track_id");

                    b.ToTable("play_event", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.Playlist.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<PlaylistKind>("Kind")
                        .HasColumnType("playlist_kind")
                        .HasColumnName("kind");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<PlaylistVisibility>("Visibility")
                        .HasColumnType("playlist_visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_playlist");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasDatabaseName("playlist_one_favorite_per_owner")
                        .HasFilter("kind = 'favorite'");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("ix_playlist_visibility")
                        .HasFilter("visibility = 'public'");

                    b.ToTable("playlist", null, t =>
                        {
                            t.HasCheckConstraint("playlist_name_length", "char_length(name) BETWEEN 1 AND 200");
                        });
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.Playlist.PlaylistItem", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("PlaylistId", "TrackId")
                        .HasName("pk_playlist_item");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_playlist_item_track_id");

                    b.ToTable("playlist_item", null, t =>
                        {
                            t.HasCheckConstraint("playlist_item_position_positive", "position >= 1");
                        });
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.Playlist.QueueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EnqueuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_queue_item");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_queue_item_track_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_queue_item_user_id");

                    b.ToTable("queue_item", null, t =>
                        {
                            t.HasCheckConstraint("queue_item_position_positive", "position >= 1");
                        });
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.Playlist.RecImpression", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Context")
                        .HasColumnType("jsonb")
                        .HasColumnName("context");

                    b.Property<DateTime>("ServedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("served_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("surface");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_rec_impression");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_rec_impression_track_id");

                    b.HasIndex("UserId", "ServedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_rec_impression_user_id_served_at");

                    b.HasIndex("UserId", "TrackId", "ServedAt")
                        .HasDatabaseName("ix_rec_impression_user_id_track_id_served_at");

                    b.ToTable("rec_impression", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.UserProfile.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_prefix");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_api_key");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_key_key_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_api_key_user_id");

                    b.ToTable("api_key", null, t =>
                        {
                            t.HasCheckConstraint("api_key_name_length", "char_length(name) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.UserProfile.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_joined");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.HasKey("Id")
                        .HasName("pk_user_profile");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profile_display_name");

                    b.ToTable("user_profile", (string)null);
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Artwork", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Asset", "SourceAsset")
                        .WithMany()
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artwork_asset_source_asset_id");

                    b.Navigation("SourceAsset");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.ArtworkVariant", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Artwork", "Artwork")
                        .WithMany("Variants")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artwork_variant_artwork_artwork_id");

                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artwork_variant_asset_asset_id");

                    b.Navigation("Artwork");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.CircleWebsite", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Circle", "Circle")
                        .WithMany("Website")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_circle_website_circle_circle_id");

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Disc", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Release", "Release")
                        .WithMany("Discs")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_disc_release_release_id");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.OriginalSong", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.OriginalWork", "OriginalWork")
                        .WithMany("Songs")
                        .HasForeignKey("OriginalWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_original_song_original_work_original_work_id");

                    b.Navigation("OriginalWork");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Release", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Artwork", "Artwork")
                        .WithMany()
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_release_artworks_artwork_id");

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.ReleaseCircle", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Circle", "Circle")
                        .WithMany("Releases")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_circle_circles_circle_id");

                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Release", "Release")
                        .WithMany("Circles")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_circle_release_release_id");

                    b.Navigation("Circle");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.SimilarCircle", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Circle", "AnchorCircle")
                        .WithMany()
                        .HasForeignKey("AnchorCircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_similar_circle_circle_anchor_circle_id");

                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Circle", "NeighborCircle")
                        .WithMany()
                        .HasForeignKey("NeighborCircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_similar_circle_circle_neighbor_circle_id");

                    b.Navigation("AnchorCircle");

                    b.Navigation("NeighborCircle");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.SimilarRelease", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Release", "AnchorRelease")
                        .WithMany()
                        .HasForeignKey("AnchorReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_similar_release_release_anchor_release_id");

                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Release", "NeighborRelease")
                        .WithMany()
                        .HasForeignKey("NeighborReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_similar_release_release_neighbor_release_id");

                    b.Navigation("AnchorRelease");

                    b.Navigation("NeighborRelease");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.SimilarTrack", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Track", "AnchorTrack")
                        .WithMany()
                        .HasForeignKey("AnchorTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_similar_track_track_anchor_track_id");

                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Track", "NeighborTrack")
                        .WithMany()
                        .HasForeignKey("NeighborTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_similar_track_track_neighbor_track_id");

                    b.Navigation("AnchorTrack");

                    b.Navigation("NeighborTrack");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Track", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Disc", "Disc")
                        .WithMany("Tracks")
                        .HasForeignKey("DiscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_disc_disc_id");

                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Lyrics", "Lyrics")
                        .WithMany()
                        .HasForeignKey("LyricsId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_track_lyrics_lyrics_id");

                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Asset", "SourceAsset")
                        .WithMany()
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_track_assets_source_asset_id");

                    b.Navigation("Disc");

                    b.Navigation("Lyrics");

                    b.Navigation("SourceAsset");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.TrackCredit", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Track", "Track")
                        .WithMany("Credits")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_credit_track_track_id");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.TrackEmbedding", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Track", "Track")
                        .WithOne()
                        .HasForeignKey("TlmcPlayerBackend.Models.MusicData.TrackEmbedding", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_embedding_track_track_id");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.TrackMapPoint", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_track_map_circle_circle_id");

                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Track", "Track")
                        .WithOne()
                        .HasForeignKey("TlmcPlayerBackend.Models.MusicData.TrackMapPoint", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_map_track_track_id");

                    b.HasOne("TlmcPlayerBackend.Models.MusicData.OriginalWork", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_track_map_original_work_work_id");

                    b.Navigation("Circle");

                    b.Navigation("Track");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.TrackOriginalSong", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.OriginalSong", "OriginalSong")
                        .WithMany("Arrangements")
                        .HasForeignKey("OriginalSongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_original_song_original_song_original_song_id");

                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Track", "Track")
                        .WithMany("OriginalSongs")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_original_song_track_track_id");

                    b.Navigation("OriginalSong");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.TrackTag", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Tag", "Tag")
                        .WithMany("Tracks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_tag_tag_tag_id");

                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Track", "Track")
                        .WithMany("Tags")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_tag_track_track_id");

                    b.Navigation("Tag");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.Playlist.PlayEvent", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_play_event_track_track_id");

                    b.HasOne("TlmcPlayerBackend.Models.UserProfile.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_play_event_user_profile_user_id");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.Playlist.Playlist", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.UserProfile.UserProfile", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_user_profile_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.Playlist.PlaylistItem", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.Playlist.Playlist", "Playlist")
                        .WithMany("Items")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_item_playlist_playlist_id");

                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_item_track_track_id");

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.Playlist.QueueItem", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_queue_item_track_track_id");

                    b.HasOne("TlmcPlayerBackend.Models.UserProfile.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_queue_item_user_profile_user_id");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.Playlist.RecImpression", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.MusicData.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rec_impression_track_track_id");

                    b.HasOne("TlmcPlayerBackend.Models.UserProfile.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rec_impression_user_profile_user_id");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.UserProfile.ApiKey", b =>
                {
                    b.HasOne("TlmcPlayerBackend.Models.UserProfile.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_user_profile_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Artwork", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Circle", b =>
                {
                    b.Navigation("Releases");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Disc", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.OriginalSong", b =>
                {
                    b.Navigation("Arrangements");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.OriginalWork", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Release", b =>
                {
                    b.Navigation("Circles");

                    b.Navigation("Discs");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Tag", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.MusicData.Track", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("OriginalSongs");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("TlmcPlayerBackend.Models.Playlist.Playlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
