apiVersion: v1
kind: Service
metadata:
  name: auth-api-clusterip
  namespace: tlmc-player
spec:
  type: ClusterIP
  selector:
    app: auth-api
  ports:
    - name: http-auth-api
      port: 80
      protocol: TCP
      targetPort: 80
      appProtocol: TCP
