apiVersion: v1
kind: Service
metadata:
  name: keycloak-server-clusterip
  namespace: tlmc-player
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - name: http-keycloak-server-port
      protocol: TCP
      port: 80
      targetPort: 80
      appProtocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-server-nodeport
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
