apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-pgsql-depl
  namespace: tlmc-player
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-pgsql-depl

  template:
    metadata:
      labels:
        app: auth-pgsql-depl

    spec:
      containers:
      - name: auth-pgsql-depl
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: postgrespw

        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb

      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: auth-pgsql-pv-claim