name: Build and Push elasticsearch with plugins Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'SearchPgSync/elasticSearch.dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/elasticsearch-plugins . -f ./SearchPgSync/elasticSearch.dockerfile

    - name: Push the Docker image
      run: |
        echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/elasticsearch-plugins
