apiVersion: v1
kind: Service
metadata:
  name: playlist-api-clusterip
  namespace: tlmc-player
spec:
  type: ClusterIP
  selector:
    app: playlist-api
  ports:
    - name: http-playlist-api
      port: 80
      protocol: TCP
      targetPort: 80
      appProtocol: HTTP
