apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-api
  namespace: tlmc-player
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist-api
  template:
    metadata:
      labels:
        app: playlist-api
    spec:
      containers:
        - name: playlist-api
          image: sqzd269/playlist-api:latest
          env:
            - name: ConnectionStrings__PostgreSql
              value: Host=playlist-pgsql-clusterip.tlmc-player.svc.cluster.local;Port=5432;Username=postgres;Password=postgrespw
            - name: Keycloak__RealmUrl
              value: https://sso.marisad.me/realms/MusicPlayer
