apiVersion: v1
kind: Service
metadata:
  name: playlist-pgsql-clusterip
  namespace: tlmc-player
spec:
  type: ClusterIP
  selector:
    app: playlist-pgsql-depl
  ports:
  - name: tcp-playlist-pgsql-db-port
    protocol: TCP
    port: 5432
    targetPort: 5432
    appProtocol: TCP
